# Generated by Django 2.0.2 on 2018-02-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180219_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paw',
            name='favourite_food',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paw',
            name='favourite_toy',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
