# Generated by Django 2.0.2 on 2018-02-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180219_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='paw',
            name='instagram',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
