# Generated by Django 2.0.2 on 2018-02-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paw_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paw',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
