# Generated by Django 2.0.2 on 2018-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_auto_20180219_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='image',
            field=models.ImageField(upload_to='organisations'),
        ),
    ]
